// schoolsData.js
const allD1Sports = [
  "Baseball", "Basketball (Men's)", "Basketball (Women's)", "Beach Volleyball", "Bowling (Women's)",
  "Cross Country (Men's)", "Cross Country (Women's)", "Fencing (Men's)", "Fencing (Women's)",
  "Field Hockey (Women's)", "Football", "Golf (Men's)", "Golf (Women's)", "Gymnastics (Men's)",
  "Gymnastics (Women's)", "Ice Hockey (Men's)", "Ice Hockey (Women's)", "Lacrosse (Men's)",
  "Lacrosse (Women's)", "Rifle", "Rowing (Women's)", "Skiing", "Soccer (Men's)", "Soccer (Women's)",
  "Softball", "Swimming & Diving (Men's)", "Swimming & Diving (Women's)", "Tennis (Men's)",
  "Tennis (Women's)", "Track & Field (Men's)", "Track & Field (Women's)", "Volleyball (Men's)",
  "Volleyball (Women's)", "Water Polo (Men's)", "Water Polo (Women's)", "Wrestling"
];

const schoolsData = [
  { universityName: "Abilene Christian University", sportsTeams: allD1Sports },
  { universityName: "Alabama Agricultural and Mechanical University", sportsTeams: allD1Sports },
  { universityName: "Alabama State University", sportsTeams: allD1Sports },
  { universityName: "Alcorn State University", sportsTeams: allD1Sports },
  { universityName: "American University", sportsTeams: allD1Sports },
  { universityName: "Appalachian State University", sportsTeams: allD1Sports },
  { universityName: "Arizona State University", sportsTeams: allD1Sports },
  { universityName: "Arkansas State University", sportsTeams: allD1Sports },
  { universityName: "Auburn University", sportsTeams: allD1Sports },
  { universityName: "Austin Peay State University", sportsTeams: allD1Sports },
  { universityName: "Ball State University", sportsTeams: allD1Sports },
  { universityName: "Baylor University", sportsTeams: allD1Sports },
  { universityName: "Bellarmine University", sportsTeams: allD1Sports },
  { universityName: "Belmont University", sportsTeams: allD1Sports },
  { universityName: "Bethune–Cookman University", sportsTeams: allD1Sports },
  { universityName: "Boise State University", sportsTeams: allD1Sports },
  { universityName: "Boston College", sportsTeams: allD1Sports },
  { universityName: "Boston University", sportsTeams: allD1Sports },
  { universityName: "Bowling Green State University", sportsTeams: allD1Sports },
  { universityName: "Bradley University", sportsTeams: allD1Sports },
  { universityName: "Brigham Young University", sportsTeams: allD1Sports },
  { universityName: "Brown University", sportsTeams: allD1Sports },
  { universityName: "Bryant University", sportsTeams: allD1Sports },
  { universityName: "Bucknell University", sportsTeams: allD1Sports },
  { universityName: "Butler University", sportsTeams: allD1Sports },
  { universityName: "California Baptist University", sportsTeams: allD1Sports },
  { universityName: "California Polytechnic State University", sportsTeams: allD1Sports },
  { universityName: "California State University, Bakersfield", sportsTeams: allD1Sports },
  { universityName: "California State University, Fresno", sportsTeams: allD1Sports },
  { universityName: "California State University, Fullerton", sportsTeams: allD1Sports },
  { universityName: "California State University, Long Beach", sportsTeams: allD1Sports },
  { universityName: "California State University, Northridge", sportsTeams: allD1Sports },
  { universityName: "California State University, Sacramento", sportsTeams: allD1Sports },
  { universityName: "Campbell University", sportsTeams: allD1Sports },
  { universityName: "Canisius University", sportsTeams: allD1Sports },
  { universityName: "Central Connecticut State University", sportsTeams: allD1Sports },
  { universityName: "Central Michigan University", sportsTeams: allD1Sports },
  { universityName: "Charleston Southern University", sportsTeams: allD1Sports },
  { universityName: "Chicago State University", sportsTeams: allD1Sports },
  { universityName: "Clemson University", sportsTeams: allD1Sports },
  { universityName: "Cleveland State University", sportsTeams: allD1Sports },
  { universityName: "Coastal Carolina University", sportsTeams: allD1Sports },
  { universityName: "Colgate University", sportsTeams: allD1Sports },
  { universityName: "College of Charleston", sportsTeams: allD1Sports },
  { universityName: "College of the Holy Cross", sportsTeams: allD1Sports },
  { universityName: "Colorado State University", sportsTeams: allD1Sports },
  { universityName: "Columbia University in the City of New York", sportsTeams: allD1Sports },
  { universityName: "Coppin State University", sportsTeams: allD1Sports },
  { universityName: "Cornell University", sportsTeams: allD1Sports },
  { universityName: "Creighton University", sportsTeams: allD1Sports },
  { universityName: "Dartmouth College", sportsTeams: allD1Sports },
  { universityName: "Davidson College", sportsTeams: allD1Sports },
  { universityName: "Delaware State University", sportsTeams: allD1Sports },
  { universityName: "DePaul University", sportsTeams: allD1Sports },
  { universityName: "Drake University", sportsTeams: allD1Sports },
  { universityName: "Drexel University", sportsTeams: allD1Sports },
  { universityName: "Duke University", sportsTeams: allD1Sports },
  { universityName: "Duquesne University of the Holy Spirit", sportsTeams: allD1Sports },
  { universityName: "East Carolina University", sportsTeams: allD1Sports },
  { universityName: "Eastern Illinois University", sportsTeams: allD1Sports },
  { universityName: "Eastern Kentucky University", sportsTeams: allD1Sports },
  { universityName: "Eastern Michigan University", sportsTeams: allD1Sports },
  { universityName: "Eastern Washington University", sportsTeams: allD1Sports },
  { universityName: "East Tennessee State University", sportsTeams: allD1Sports },
  { universityName: "East Texas A&M University", sportsTeams: allD1Sports },
  { universityName: "Elon University", sportsTeams: allD1Sports },
  { universityName: "Fairfield University", sportsTeams: allD1Sports },
  { universityName: "Fairleigh Dickinson University", sportsTeams: allD1Sports },
  { universityName: "Florida Agricultural and Mechanical University", sportsTeams: allD1Sports },
  { universityName: "Florida Atlantic University", sportsTeams: allD1Sports },
  { universityName: "Florida Gulf Coast University", sportsTeams: allD1Sports },
  { universityName: "Florida International University", sportsTeams: allD1Sports },
  { universityName: "Florida State University", sportsTeams: allD1Sports },
  { universityName: "Fordham University", sportsTeams: allD1Sports },
  { universityName: "Furman University", sportsTeams: allD1Sports },
  { universityName: "Gardner–Webb University", sportsTeams: allD1Sports },
  { universityName: "George Mason University", sportsTeams: allD1Sports },
  { universityName: "Georgetown University", sportsTeams: allD1Sports },
  { universityName: "Georgia Institute of Technology", sportsTeams: allD1Sports },
  { universityName: "Georgia Southern University", sportsTeams: allD1Sports },
  { universityName: "Georgia State University", sportsTeams: allD1Sports },
  { universityName: "Gonzaga University", sportsTeams: allD1Sports },
  { universityName: "Grambling State University", sportsTeams: allD1Sports },
  { universityName: "Grand Canyon University", sportsTeams: allD1Sports },
  { universityName: "Hampton University", sportsTeams: allD1Sports },
  { universityName: "Harvard University", sportsTeams: allD1Sports },
  { universityName: "High Point University", sportsTeams: allD1Sports },
  { universityName: "Hofstra University", sportsTeams: allD1Sports },
  { universityName: "Houston Christian University", sportsTeams: allD1Sports },
  { universityName: "Howard University", sportsTeams: allD1Sports },
  { universityName: "Idaho State University", sportsTeams: allD1Sports },
  { universityName: "Illinois State University", sportsTeams: allD1Sports },
  { universityName: "Indiana State University", sportsTeams: allD1Sports },
  { universityName: "Indiana University Bloomington", sportsTeams: allD1Sports },
  { universityName: "Indiana University Indianapolis", sportsTeams: allD1Sports },
  { universityName: "Iona University", sportsTeams: allD1Sports },
  { universityName: "Iowa State University of Science and Technology", sportsTeams: allD1Sports },
  { universityName: "Jackson State University", sportsTeams: allD1Sports },
  { universityName: "Jacksonville State University", sportsTeams: allD1Sports },
  { universityName: "Jacksonville University", sportsTeams: allD1Sports },
  { universityName: "James Madison University", sportsTeams: allD1Sports },
  { universityName: "Kansas State University", sportsTeams: allD1Sports },
  { universityName: "Kennesaw State University", sportsTeams: allD1Sports },
  { universityName: "Kent State University", sportsTeams: allD1Sports },
  { universityName: "Lafayette College", sportsTeams: allD1Sports },
  { universityName: "Lamar University", sportsTeams: allD1Sports },
  { universityName: "La Salle University", sportsTeams: allD1Sports },
  { universityName: "Lehigh University", sportsTeams: allD1Sports },
  { universityName: "Leland Stanford Junior University", sportsTeams: allD1Sports },
  { universityName: "Liberty University", sportsTeams: allD1Sports },
  { universityName: "Lindenwood University", sportsTeams: allD1Sports },
  { universityName: "Lipscomb University", sportsTeams: allD1Sports },
  { universityName: "Long Island University", sportsTeams: allD1Sports },
  { universityName: "Longwood University", sportsTeams: allD1Sports },
  { universityName: "Louisiana State University and Agricultural and Mechanical College", sportsTeams: allD1Sports },
  { universityName: "Louisiana Tech University", sportsTeams: allD1Sports },
  { universityName: "Loyola Marymount University", sportsTeams: allD1Sports },
  { universityName: "Loyola University Chicago", sportsTeams: allD1Sports },
  { universityName: "Loyola University Maryland", sportsTeams: allD1Sports },
  { universityName: "Manhattan University", sportsTeams: allD1Sports },
  { universityName: "Marist College", sportsTeams: allD1Sports },
  { universityName: "Marquette University", sportsTeams: allD1Sports },
  { universityName: "Marshall University", sportsTeams: allD1Sports },
  { universityName: "McNeese State University", sportsTeams: allD1Sports },
  { universityName: "Mercer University", sportsTeams: allD1Sports },
  { universityName: "Merrimack College", sportsTeams: allD1Sports },
  { universityName: "Miami University", sportsTeams: allD1Sports },
  { universityName: "Michigan State University", sportsTeams: allD1Sports },
  { universityName: "Middle Tennessee State University", sportsTeams: allD1Sports },
  { universityName: "Mississippi State University", sportsTeams: allD1Sports },
  { universityName: "Mississippi Valley State University", sportsTeams: allD1Sports },
  { universityName: "Missouri State University", sportsTeams: allD1Sports },
  { universityName: "Monmouth University", sportsTeams: allD1Sports },
  { universityName: "Montana State University", sportsTeams: allD1Sports },
  { universityName: "Morehead State University", sportsTeams: allD1Sports },
  { universityName: "Morgan State University", sportsTeams: allD1Sports },
  { universityName: "Mount Saint Mary's University", sportsTeams: allD1Sports },
  { universityName: "Murray State University", sportsTeams: allD1Sports },
  { universityName: "New Jersey Institute of Technology", sportsTeams: allD1Sports },
  { universityName: "New Mexico State University", sportsTeams: allD1Sports },
  { universityName: "Niagara University", sportsTeams: allD1Sports },
  { universityName: "Nicholls State University", sportsTeams: allD1Sports },
  { universityName: "Norfolk State University", sportsTeams: allD1Sports },
  { universityName: "North Carolina Agricultural and Technical State University", sportsTeams: allD1Sports },
  { universityName: "North Carolina Central University", sportsTeams: allD1Sports },
  { universityName: "North Carolina State University", sportsTeams: allD1Sports },
  { universityName: "North Dakota State University of Agriculture and Applied Sciences", sportsTeams: allD1Sports },
  { universityName: "Northeastern University", sportsTeams: allD1Sports },
  { universityName: "Northern Arizona University", sportsTeams: allD1Sports },
  { universityName: "Northern Illinois University", sportsTeams: allD1Sports },
  { universityName: "Northern Kentucky University", sportsTeams: allD1Sports },
  { universityName: "Northwestern State University of Louisiana", sportsTeams: allD1Sports },
  { universityName: "Northwestern University", sportsTeams: allD1Sports },
  { universityName: "Oakland University", sportsTeams: allD1Sports },
  { universityName: "Oklahoma State University–Stillwater", sportsTeams: allD1Sports },
  { universityName: "Old Dominion University", sportsTeams: allD1Sports },
  { universityName: "Oral Roberts University", sportsTeams: allD1Sports },
  { universityName: "Oregon State University", sportsTeams: allD1Sports },
  { universityName: "Pepperdine University", sportsTeams: allD1Sports },
  { universityName: "Portland State University", sportsTeams: allD1Sports },
  { universityName: "Prairie View A&M University", sportsTeams: allD1Sports },
  { universityName: "Presbyterian College", sportsTeams: allD1Sports },
  { universityName: "Princeton University", sportsTeams: allD1Sports },
  { universityName: "Providence College", sportsTeams: allD1Sports },
  { universityName: "Purdue University", sportsTeams: allD1Sports },
  { universityName: "Purdue University Fort Wayne", sportsTeams: allD1Sports },
  { universityName: "Queens University of Charlotte", sportsTeams: allD1Sports },
  { universityName: "Quinnipiac University", sportsTeams: allD1Sports },
  { universityName: "Radford University", sportsTeams: allD1Sports },
  { universityName: "Rider University", sportsTeams: allD1Sports },
  { universityName: "Robert Morris University", sportsTeams: allD1Sports },
  { universityName: "Rutgers University–New Brunswick", sportsTeams: allD1Sports },
  { universityName: "Sacred Heart University", sportsTeams: allD1Sports },
  { universityName: "Saint Bonaventure University", sportsTeams: allD1Sports },
  { universityName: "Saint Francis University", sportsTeams: allD1Sports },
  { universityName: "Saint John's University", sportsTeams: allD1Sports },
  { universityName: "Saint Joseph's University", sportsTeams: allD1Sports },
  { universityName: "Saint Louis University", sportsTeams: allD1Sports },
  { universityName: "Saint Mary's College of California", sportsTeams: allD1Sports },
  { universityName: "Saint Peter's University", sportsTeams: allD1Sports },
  { universityName: "Sam Houston State University", sportsTeams: allD1Sports },
  { universityName: "Samford University", sportsTeams: allD1Sports },
  { universityName: "San Diego State University", sportsTeams: allD1Sports },
  { universityName: "San Jose State University", sportsTeams: allD1Sports },
  { universityName: "Santa Clara University", sportsTeams: allD1Sports },
  { universityName: "Seattle University", sportsTeams: allD1Sports },
  { universityName: "Seton Hall University", sportsTeams: allD1Sports },
  { universityName: "Siena College", sportsTeams: allD1Sports },
  { universityName: "South Carolina State University", sportsTeams: allD1Sports },
  { universityName: "South Dakota State University", sportsTeams: allD1Sports },
  { universityName: "Southeast Missouri State University", sportsTeams: allD1Sports },
  { universityName: "Southeastern Louisiana University", sportsTeams: allD1Sports },
  { universityName: "Southern University and A&M College", sportsTeams: allD1Sports },
  { universityName: "Southern Illinois University Carbondale", sportsTeams: allD1Sports },
  { universityName: "Southern Illinois University Edwardsville", sportsTeams: allD1Sports },
  { universityName: "Southern Methodist University", sportsTeams: allD1Sports },
  { universityName: "Southern Utah University", sportsTeams: allD1Sports },
  { universityName: "State University of Iowa", sportsTeams: allD1Sports },
  { universityName: "State University of New York at Albany", sportsTeams: allD1Sports },
  { universityName: "State University of New York at Binghamton", sportsTeams: allD1Sports },
  { universityName: "State University of New York at Buffalo", sportsTeams: allD1Sports },
  { universityName: "State University of New York at Stony Brook", sportsTeams: allD1Sports },
  { universityName: "Stephen F. Austin State University", sportsTeams: allD1Sports },
  { universityName: "Stetson University", sportsTeams: allD1Sports },
  { universityName: "Stonehill College", sportsTeams: allD1Sports },
  { universityName: "Syracuse University", sportsTeams: allD1Sports },
  { universityName: "Tarleton State University", sportsTeams: allD1Sports },
  { universityName: "Temple University", sportsTeams: allD1Sports },
  { universityName: "Tennessee State University", sportsTeams: allD1Sports },
  { universityName: "Tennessee Technological University", sportsTeams: allD1Sports },
  { universityName: "Texas A&M University", sportsTeams: allD1Sports },
  { universityName: "Texas A&M University–Corpus Christi", sportsTeams: allD1Sports },
  { universityName: "Texas Christian University", sportsTeams: allD1Sports },
  { universityName: "Texas Southern University", sportsTeams: allD1Sports },
  { universityName: "Texas State University", sportsTeams: allD1Sports },
  { universityName: "Texas Tech University", sportsTeams: allD1Sports },
  { universityName: "The Citadel, The Military College of South Carolina", sportsTeams: allD1Sports },
  { universityName: "The College of William and Mary in Virginia", sportsTeams: allD1Sports },
  { universityName: "The George Washington University", sportsTeams: allD1Sports },
  { universityName: "The Ohio State University", sportsTeams: allD1Sports },
  { universityName: "The Ohio University", sportsTeams: allD1Sports },
  { universityName: "The Pennsylvania State University", sportsTeams: allD1Sports },
  { universityName: "The University of Akron", sportsTeams: allD1Sports },
  { universityName: "The University of Alabama", sportsTeams: allD1Sports },
  { universityName: "The University of Mississippi", sportsTeams: allD1Sports },
  { universityName: "The University of New Mexico", sportsTeams: allD1Sports },
  { universityName: "The University of Tennessee at Chattanooga", sportsTeams: allD1Sports },
  { universityName: "The University of Tennessee at Martin", sportsTeams: allD1Sports },
  { universityName: "The University of Tennessee, Knoxville", sportsTeams: allD1Sports },
  { universityName: "The University of Texas at Arlington", sportsTeams: allD1Sports },
  { universityName: "The University of Texas at Austin", sportsTeams: allD1Sports },
  { universityName: "The University of Texas at El Paso", sportsTeams: allD1Sports },
  { universityName: "The University of Texas Rio Grande Valley", sportsTeams: allD1Sports },
  { universityName: "The University of Texas at San Antonio", sportsTeams: allD1Sports },
  { universityName: "The University of Tulsa", sportsTeams: allD1Sports },
  { universityName: "The University of Vermont and State Agricultural College", sportsTeams: allD1Sports },
  { universityName: "Towson University", sportsTeams: allD1Sports },
  { universityName: "Troy University", sportsTeams: allD1Sports },
  { universityName: "Tulane University of Louisiana", sportsTeams: allD1Sports },
  { universityName: "United States Air Force Academy", sportsTeams: allD1Sports },
  { universityName: "United States Military Academy", sportsTeams: allD1Sports },
  { universityName: "United States Naval Academy", sportsTeams: allD1Sports },
  { universityName: "University of Alabama at Birmingham", sportsTeams: allD1Sports },
  { universityName: "University of Arizona", sportsTeams: allD1Sports },
  { universityName: "University of Arkansas", sportsTeams: allD1Sports },
  { universityName: "University of Arkansas at Little Rock", sportsTeams: allD1Sports },
  { universityName: "University of Arkansas at Pine Bluff", sportsTeams: allD1Sports },
  { universityName: "University of California, Berkeley", sportsTeams: allD1Sports },
  { universityName: "University of California, Davis", sportsTeams: allD1Sports },
  { universityName: "University of California, Irvine", sportsTeams: allD1Sports },
  { universityName: "University of California, Los Angeles", sportsTeams: allD1Sports },
  { universityName: "University of California, Riverside", sportsTeams: allD1Sports },
  { universityName: "University of California, San Diego", sportsTeams: allD1Sports },
  { universityName: "University of California, Santa Barbara", sportsTeams: allD1Sports },
  { universityName: "University of Central Arkansas", sportsTeams: allD1Sports },
  { universityName: "University of Central Florida", sportsTeams: allD1Sports },
  { universityName: "University of Cincinnati", sportsTeams: allD1Sports },
  { universityName: "University of Colorado Boulder", sportsTeams: allD1Sports },
  { universityName: "University of Connecticut", sportsTeams: allD1Sports },
  { universityName: "University of Dayton", sportsTeams: allD1Sports },
  { universityName: "University of Delaware", sportsTeams: allD1Sports },
  { universityName: "University of Denver", sportsTeams: allD1Sports },
  { universityName: "University of Detroit Mercy", sportsTeams: allD1Sports },
  { universityName: "University of Evansville", sportsTeams: allD1Sports },
  { universityName: "University of Florida", sportsTeams: allD1Sports },
  { universityName: "University of Georgia", sportsTeams: allD1Sports },
  { universityName: "University of Hawaiʻi at Mānoa", sportsTeams: allD1Sports },
  { universityName: "University of Houston", sportsTeams: allD1Sports },
  { universityName: "University of Idaho", sportsTeams: allD1Sports },
  { universityName: "University of Illinois Chicago", sportsTeams: allD1Sports },
  { universityName: "University of Illinois Urbana-Champaign", sportsTeams: allD1Sports },
  { universityName: "University of Kansas", sportsTeams: allD1Sports },
  { universityName: "University of Kentucky", sportsTeams: allD1Sports },
  { universityName: "University of Louisiana at Lafayette", sportsTeams: allD1Sports },
  { universityName: "University of Louisiana at Monroe", sportsTeams: allD1Sports },
  { universityName: "University of Louisville", sportsTeams: allD1Sports },
  { universityName: "University of Maine", sportsTeams: allD1Sports },
  { universityName: "University of Maryland, Baltimore County", sportsTeams: allD1Sports },
  { universityName: "University of Maryland, College Park", sportsTeams: allD1Sports },
  { universityName: "University of Maryland Eastern Shore", sportsTeams: allD1Sports },
  { universityName: "University of Massachusetts Amherst", sportsTeams: allD1Sports },
  { universityName: "University of Massachusetts Lowell", sportsTeams: allD1Sports },
  { universityName: "University of Memphis", sportsTeams: allD1Sports },
  { universityName: "University of Miami", sportsTeams: allD1Sports },
  { universityName: "University of Michigan", sportsTeams: allD1Sports },
  { universityName: "University of Minnesota", sportsTeams: allD1Sports },
  { universityName: "University of Missouri–Columbia", sportsTeams: allD1Sports },
  { universityName: "University of Missouri–Kansas City", sportsTeams: allD1Sports },
  { universityName: "University of Montana", sportsTeams: allD1Sports },
  { universityName: "University of Nebraska–Lincoln", sportsTeams: allD1Sports },
  { universityName: "University of Nebraska Omaha", sportsTeams: allD1Sports },
  { universityName: "University of Nevada, Las Vegas", sportsTeams: allD1Sports },
  { universityName: "University of Nevada, Reno", sportsTeams: allD1Sports },
  { universityName: "University of New Hampshire", sportsTeams: allD1Sports },
  { universityName: "University of New Orleans", sportsTeams: allD1Sports },
  { universityName: "University of North Alabama", sportsTeams: allD1Sports },
  { universityName: "University of North Carolina at Asheville", sportsTeams: allD1Sports },
  { universityName: "University of North Carolina at Chapel Hill", sportsTeams: allD1Sports },
  { universityName: "University of North Carolina at Charlotte", sportsTeams: allD1Sports },
  { universityName: "University of North Carolina at Greensboro", sportsTeams: allD1Sports },
  { universityName: "University of North Carolina at Wilmington", sportsTeams: allD1Sports },
  { universityName: "University of North Dakota", sportsTeams: allD1Sports },
  { universityName: "University of Northern Colorado", sportsTeams: allD1Sports },
  { universityName: "University of Northern Iowa", sportsTeams: allD1Sports },
  { universityName: "University of North Florida", sportsTeams: allD1Sports },
  { universityName: "University of North Texas", sportsTeams: allD1Sports },
  { universityName: "University of Notre Dame du Lac", sportsTeams: allD1Sports },
  { universityName: "University of Oklahoma", sportsTeams: allD1Sports },
  { universityName: "University of Oregon", sportsTeams: allD1Sports },
  { universityName: "University of Pennsylvania", sportsTeams: allD1Sports },
  { universityName: "University of Pittsburgh", sportsTeams: allD1Sports },
  { universityName: "University of Portland", sportsTeams: allD1Sports },
  { universityName: "University of Rhode Island", sportsTeams: allD1Sports },
  { universityName: "University of Richmond", sportsTeams: allD1Sports },
  { universityName: "University of Saint Thomas", sportsTeams: allD1Sports },
  { universityName: "University of San Diego", sportsTeams: allD1Sports },
  { universityName: "University of San Francisco", sportsTeams: allD1Sports },
  { universityName: "University of South Alabama", sportsTeams: allD1Sports },
  { universityName: "University of South Carolina", sportsTeams: allD1Sports },
  { universityName: "University of South Carolina Upstate", sportsTeams: allD1Sports },
  { universityName: "University of South Dakota", sportsTeams: allD1Sports },
  { universityName: "University of Southern California", sportsTeams: allD1Sports },
  { universityName: "University of Southern Indiana", sportsTeams: allD1Sports },
  { universityName: "University of Southern Mississippi", sportsTeams: allD1Sports },
  { universityName: "University of South Florida", sportsTeams: allD1Sports },
  { universityName: "University of the Incarnate Word", sportsTeams: allD1Sports },
  { universityName: "University of the Pacific", sportsTeams: allD1Sports },
  { universityName: "University of Toledo", sportsTeams: allD1Sports },
  { universityName: "University of Utah", sportsTeams: allD1Sports },
  { universityName: "University of Virginia", sportsTeams: allD1Sports },
  { universityName: "University of Washington", sportsTeams: allD1Sports },
  { universityName: "University of Wisconsin–Green Bay", sportsTeams: allD1Sports },
  { universityName: "University of Wisconsin–Madison", sportsTeams: allD1Sports },
  { universityName: "University of Wisconsin–Milwaukee", sportsTeams: allD1Sports },
  { universityName: "University of Wyoming", sportsTeams: allD1Sports },
  { universityName: "Utah State University", sportsTeams: allD1Sports },
  { universityName: "Utah Tech University", sportsTeams: allD1Sports },
  { universityName: "Utah Valley University", sportsTeams: allD1Sports },
  { universityName: "Valparaiso University", sportsTeams: allD1Sports },
  { universityName: "Vanderbilt University", sportsTeams: allD1Sports },
  { universityName: "Villanova University", sportsTeams: allD1Sports },
  { universityName: "Virginia Commonwealth University", sportsTeams: allD1Sports },
  { universityName: "Virginia Military Institute", sportsTeams: allD1Sports },
  { universityName: "Virginia Polytechnic Institute and State University", sportsTeams: allD1Sports },
  { universityName: "Wagner College", sportsTeams: allD1Sports },
  { universityName: "Wake Forest University", sportsTeams: allD1Sports },
  { universityName: "Washington State University", sportsTeams: allD1Sports },
  { universityName: "Weber State University", sportsTeams: allD1Sports },
  { universityName: "Western Carolina University", sportsTeams: allD1Sports },
  { universityName: "Western Illinois University", sportsTeams: allD1Sports },
  { universityName: "Western Kentucky University", sportsTeams: allD1Sports },
  { universityName: "Western Michigan University", sportsTeams: allD1Sports },
  { universityName: "West Virginia University", sportsTeams: allD1Sports },
  { universityName: "Wichita State University", sportsTeams: allD1Sports },
  { universityName: "William Marsh Rice University", sportsTeams: allD1Sports },
  { universityName: "Winthrop University", sportsTeams: allD1Sports },
  { universityName: "Wofford College", sportsTeams: allD1Sports },
  { universityName: "Wright State University", sportsTeams: allD1Sports },
  { universityName: "Xavier University", sportsTeams: allD1Sports },
  { universityName: "Yale University", sportsTeams: allD1Sports },
  { universityName: "Youngstown State University", sportsTeams: allD1Sports },
];

module.exports = schoolsData;